# Generated by Django 5.1 on 2024-08-31 07:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=200, unique=True)),
                ('property_type', models.CharField(choices=[('Commercial', 'Commericial'), ('Private', 'Private')], default='Private', max_length=10)),
                ('units', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('current_units', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, validators=[django.core.validators.RegexValidator(message='Alphabet characters and spaces are only allowed.', regex='^[a-zA-z\\s]*$')])),
                ('lease_start', models.DateTimeField()),
                ('lease_end', models.DateTimeField()),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=14)),
                ('unit', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LeaseManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('properties', models.ManyToManyField(related_name='lease_manager', to='erp_app.property')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='tenants',
            field=models.ManyToManyField(blank=True, related_name='properties', to='erp_app.tenant'),
        ),
        migrations.CreateModel(
            name='UnitRoom',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('unit_number', models.CharField(max_length=10, unique=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_rooms', to='erp_app.property')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant', to='erp_app.tenant')),
            ],
        ),
    ]
