# Generated by Django 5.1 on 2024-09-01 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0002_alter_unitroom_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='next_payment_due',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
