# Generated by Django 5.1 on 2024-09-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0003_tenant_next_payment_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='lease_end',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='lease_start',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='monthly_rent',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=14),
        ),
    ]
